### ISSUE TITLE
pe_unmapper

### ISSUE THREAD

**Issue by TishSerg** [hasherezade/pe_utils#1]
Hello, hasherezade! I'm not sure if it's right place for this question, but still...

I tried to use your tool as it intended to be used. 2 dll dumped from memory are successfully converted. But 1 of them results in 0 bytes... 
[Here is that die hard dll](https://drive.google.com/file/d/1BMZFBUUOyIcz4YWvcHxzwRkBAx4hHWfH/view?usp=sharing)
Could you check why `pe_unmapper` produces 0 bytes output from that dll, please?

I got your tool from [here](https://web.archive.org/web/20181104111048if_/https://github.com/hasherezade/pe_recovery_tools/tree/master/pe_unmapper)
BTW, why that repo no longer exist? Or it was renamed to something else?
Anyways, thank you for that piece of soft.

**Comment by hasherezade** [comment]
hi! I don't recommend using the version from WebArchive, since it is a very old version! `pe_unmapper` is still maintained, just it is now stored somewhere else, as a part of the `libpeconv` project:
https://github.com/hasherezade/libpeconv/tree/master/pe_unmapper

**Comment by hasherezade** [comment]
I checked it and I see that the new version had no problem converting your file. I am attaching the output here (password: `demodemo`):
[drBase_0x01b63f050000_unmapped.dll.zip](https://github.com/hasherezade/pe_utils/files/6832614/drBase_0x01b63f050000_unmapped.dll.zip)

**Comment by TishSerg** [comment]
Thank you! 
Glad to see your tool is not just alive but even more advanced.
Just checked other stuff on your site... I'm almost nothing have to do with reversing and when I see such skilled people in this... What I want to say is WOW. Just WOW.
