### ISSUE TITLE
pe_check produces no output

### ISSUE THREAD

**Issue by morrowd** [hasherezade/pe_utils#2]
Could be me but when I test the pe_check.exe release 1.0 on a couple of PE files it isn't producing any output/nothing to stdout
![pe_check_screenshot](https://user-images.githubusercontent.com/6360672/134074065-b554b0f1-2600-4b85-8f2b-b9421335b7bf.png)
.

**Comment by hasherezade** [comment]
the output of pe_check is its return value. you can check it by:
```
echo %errorlevel%
```
Example:

![pe_check_example](https://user-images.githubusercontent.com/3115348/134076260-5959de51-3925-4c04-b480-ada9bea028ba.png)

**Comment by morrowd** [comment]
I was executing through PowerShell and Windows Terminal Preview at first. I tried good old cmd.exe and return value is displayed with echo %errorlevel%

**Comment by hasherezade** [comment]
ok, so I believe your problem is solved? if so, please close the issue.

**Comment by morrowd** [comment]
Thanks for the quick response. Closing issue.
